 # ---------------------------------------------------------
# DAY 1 TASK: Base DevSecOps Pipeline & Build/Test Job
# ---------------------------------------------------------

# Pipeline Name
name: DevSecOps Pipeline

# Pipeline Triggers (When to run the pipeline)
on:
  push:
    # Runs when code is pushed to your feature branch or main
    branches: [ "it24100822-member-4-devsecops", "main" ]
  pull_request:
    # Runs when a pull request is created for main branch
    branches: [ "main" ]

# Pipeline Jobs
jobs:
  # Job 1: Build the project and run unit tests
  build-and-test:
    name: Build & Unit Tests
    # Runner environment (Latest Ubuntu Linux runner)
    runs-on: ubuntu-latest

    # Sequence of tasks/steps in this job
    steps:
      # Step 1: Checkout repository code to the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK 17)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          # Target Java version
          java-version: '21'
          # JDK distribution provider
          distribution: 'temurin'
          # Cache Maven dependencies to speed up future builds
          cache: maven

      # Step 3: Build application and compile unit tests using Maven
      - name: Build with Maven
        # Run Maven wrapper command (clean and compile tests)
        run: ./mvnw --batch-mode --no-transfer-progress clean test-compile
